name: bandit-server
version: 0.1.0.0
github: "bartfrenk/bandit-server"
license: BSD3
author: "Bart Frenk"
maintainer: "bart.frenk@gmail.com"
copyright: "2018 Bart Frenk"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: >-
  Server to run multi-armed bandit experiments
category: Web

description: >-
  Please see the README on Github at
  <https://github.com/githubuser/bandit-server#readme>

dependencies:
- base >= 4.7 && < 5
- bandit-agents

library:
  source-dirs: src

executables:
  bandit-server-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bandit-server

tests:
  bandit-server-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bandit-server
